## Gradle
org.gradle.jvmargs=-Xmx4g --enable-native-access=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
org.gradle.configuration-cache.problems=warn
org.gradle.kotlin.dsl.allWarningsAsErrors=true

## Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096m --enable-native-access=ALL-UNNAMED
kotlin.jvm.target.validation.mode=warning
kotlin.build.report.output=build_scan

## Kotlin/JS
kotlin.js.yarn=false

## KotlinNative
kotlin.incremental.native=true
kotlin.native.binary.gc=cms
kotlin.native.ignoreDisabledTargets=true
kotlin.native.enableKlibsCrossCompilation=true
# kotlin.native.toolchain.enabled=false
# kotlin.mpp.enableCInteropCommonization=true

## Dokka
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
org.jetbrains.dokka.experimental.tryK2=true
org.jetbrains.dokka.experimental.tryK2.nowarn=true

## KSP
ksp.version.check=false